#!/bin/bash
echo "'" | sudo echo hi
date
echo going for sleep 10
sleep 10
date
echo came from sleep
date
echo system_is_nw_started_done
date
echo id is $1


vms=`cat VMS`

echo came from sleep


echo "'" | sudo -S ./trace.sh &
id=`echo $!`
date
echo $id

#date
#./vm "echo 0 > /proc/sys/kernel/randomization_va_space"
#date
#./vm "sudo rm -rf /mnt/*"
#date
#./vm "filebench -f /home/shubhamiit/workload/ws.f" > bench.out
#date

#./vm "filebench -f /home/shubhamiit/workload/ws.f" > bench.out
#./vm "/home/shubhamiit/workload/writefile /home/shubhamiit/workload/file1 .6 r 1024 600 10007" > bench.out

date
echo "start mybench"
if [[ $vms == 1 ]];then
	./vmc1 "/home/shubhamiit/workload/perf_mybench" > bench.out1
fi
if [[ $vms == 2 ]];then
        
	./vmc1 "/home/shubhamiit/workload/perf_mybench" > bench.out1  &
        idvmc1=$! 
        ./vmc2 "/home/shubhamiit/workload/perf_mybench" > bench.out2  &
        idvmc2=$! 

        echo $idvmc1 $idvmc2 

        wait $idvmc1 $idvmc2 

        

        echo "mybench finished"
        
fi

if [[ $vms == 4 ]];then

	./vmc1 "/home/shubhamiit/workload/perf_mybench" > bench.out1  &
        idvmc1=$!
        ./vmc2 "/home/shubhamiit/workload/perf_mybench" > bench.out2  &
        idvmc2=$!
	./vmc3 "/home/shubhamiit/workload/perf_mybench" > bench.out3  &
        idvmc3=$!
        ./vmc4 "/home/shubhamiit/workload/perf_mybench" > bench.out4  &
        idvmc4=$!
        wait $idvmc1 $idvmc2 $idvmc3 $idvmc4

        echo "mybench finished"
        
fi

date

echo "'" | sudo -S kill $id
#killall parse_tmem_stat
echo "'" | sudo -S kill `ps -e | grep parse_tmem_stat | sed 's/[ ]*\(.*\)/\1/' | cut -d" " -f1`


rm -rf "$1".setup
mkdir "$1".setup

echo "'" | sudo -S xm dmesg | grep "Command line" > boot_line
echo "'" | sudo -S xm tmem-list -al > stats_tmem
echo "'" | sudo -S xm info > stats_xen
echo "'" | sudo -S xl tmem-list -ag > stats_list_get
echo "'" | sudo -S xl tmem-list -ap > stats_list_put
echo "'" | sudo -S xl tmem-list -af > stats_list_fget
echo "'" | sudo -S xl tmem-list -aq > stats_list_fput
echo "'" | sudo -S xl tmem-list -ac > stats_list_comp
echo "'" | sudo -S xl tmem-list -ad > stats_list_dedup
echo "'" | sudo -S xl tmem-list -ae > stats_list_fdedup
echo "'" | sudo -S xl tmem-list -au > stats_list_decom

mv stats* "$1".setup/
mv bench.out* "$1".setup/
mv boot_line "$1".setup/
date
echo going for reboot

sudo xm shutdown vm1
sudo xm shutdown vm2
sudo xm shutdown vm3
sudo xm shutdown vm4
sleep 15


sudo xm list >> logs

echo vm destroyed >> logs

exit 0


