#! /bin/bash

cd /home/shubhamiit/final_expr

date >> logs
echo going for sleep 40 >> logs
sleep 40
date >> logs
echo came from sleep >> logs

date >> logs
echo "system started" >> logs
echo "stupid things" >> logs


vms=`cat VMS`
echo "Vms are $vms" >> logs

curr=`cat current_count`

echo current count is $curr >> logs
fcount=`cat fcount`


echo fcount is $fcount >> logs

if [[ $curr == 8 ]];then
    exit 0
fi



vms=`cat VMS`
if [[ $vms == 1 ]];then
        sudo xm create vm1 >> logs
fi
if [[ $vms == 2 ]];then
        sudo xm create vm1   >> logs
        sleep 20
        sudo xm create vm2  >> logs

fi
if [[ $vms == 4 ]];then
        sudo xm create vm1   >> logs  
        sleep 20
        sudo xm create vm2  >> logs  
        sleep 20
        sudo xm create vm3  >> logs  
        sleep 20
        sudo xm create vm4  >> logs  
                
fi
date >> logs
echo going to sleep 20 >> logs
sleep 60 
echo going for checking >> logs
date >> logs
offtime=0
one=1
while [[ $one == 1 ]]
do
    offtime=$(( $offtime + 1 ))
    if [[ $offtime == 5 ]];then
        offtime=0
        sudo xm shutdown vm1    >> logs  
        sudo xm shutdown vm2  >> logs  
        sudo xm shutdown vm3  >> logs  
        sudo xm shutdown vm4  >> logs  
        sleep 25
        sudo xm destroy vm1  >> logs  
        sudo xm destroy vm2  >> logs  
        sudo xm destroy vm3  >> logs  
        sudo xm destroy vm4  >> logs  
                
        sudo e2fsck -y /dev/vg_xen/vm1_disk   >> logs  
        sudo e2fsck -y /dev/vg_xen/vm2_disk  >> logs  
        sudo e2fsck -y /dev/vg_xen/vm3_disk  >> logs  
        sudo e2fsck -y /dev/vg_xen/vm4_disk  >> logs  
        sudo e2fsck -y /dev/vg_xen/vm1_disk  >> logs  
        sudo e2fsck -y /dev/vg_xen/vm2_disk  >> logs  
        sudo e2fsck -y /dev/vg_xen/vm3_disk  >> logs  
        sudo e2fsck -y /dev/vg_xen/vm4_disk  >> logs  

        if [[ $vms == 1 ]];then
        sudo xm create vm1  >> logs  
        fi

        if [[ $vms == 2 ]];then
            sudo xm create vm1  >> logs  
        sleep 20
            sudo xm create vm2  >> logs  
        fi

        if [[ $vms == 4 ]];then
            sudo xm create vm1  >> logs  
        sleep 20
            sudo xm create vm2  >> logs  
        sleep 20
            sudo xm create vm3  >> logs  
        sleep 20
            sudo xm create vm4  >> logs  
        fi

        sleep 60
        
    fi


    sudo rm check_ok*

    date
    chdate=`date +%y%m%d%H%M%S`
    if [[ $vms == 1 ]];then
        
        
    ./vmc1 "touch /home/shubhamiit/check/$chdate; ls /home/shubhamiit/check/$chdate;rm /home/shubhamiit/check/$chdate" > check_ok1 &
        idc=`echo $!`
        sleep 10
        kill $idc
        if [[ `cat check_ok1` ]];then
                echo "okay to start" >> logs
        break
        fi
        echo "not okay" >> logs
    continue
    fi

    if [[ $vms == 2 ]];then
    ./vmc1 "touch /home/shubhamiit/check/$chdate; ls /home/shubhamiit/check/$chdate;rm /home/shubhamiit/check/$chdate" > check_ok1 &
        idc1=`echo $!`
    
    ./vmc2 "touch /home/shubhamiit/check/$chdate; ls /home/shubhamiit/check/$chdate;rm /home/shubhamiit/check/$chdate" > check_ok2 &
        idc2=`echo $!`
    
    
        sleep 10
        kill $idc1
    kill $idc2
        if [[ `cat check_ok1` ]];then
        if [[ `cat check_ok2` ]];then
                    echo "okay to start" >> logs
            break
        fi
        fi
        echo "not okay" >> logs
    continue

    fi

    if [[ $vms == 4 ]];then
    ./vmc1 "touch /home/shubhamiit/check/$chdate; ls /home/shubhamiit/check/$chdate;rm /home/shubhamiit/check/$chdate" > check_ok1 &
        idc1=`echo $!`  
    ./vmc2 "touch /home/shubhamiit/check/$chdate; ls /home/shubhamiit/check/$chdate;rm /home/shubhamiit/check/$chdate" > check_ok2 &
        idc2=`echo $!`
    ./vmc3 "touch /home/shubhamiit/check/$chdate; ls /home/shubhamiit/check/$chdate;rm /home/shubhamiit/check/$chdate" > check_ok3 &
        idc3=`echo $!`
    ./vmc4 "touch /home/shubhamiit/check/$chdate; ls /home/shubhamiit/check/$chdate;rm /home/shubhamiit/check/$chdate" > check_ok4 &
        idc4=`echo $!`
    
    #grep -P "\sro[\s,]" /proc/mounts
        sleep 10
        kill $idc1
    kill $idc2
    kill $idc3
    kill $idc4

        if [[ `cat check_ok1` ]];then
        if [[ `cat check_ok2` ]];then
            if [[ `cat check_ok3` ]];then
                if [[ `cat check_ok4` ]];then
                                        echo "okay to start"  >> logs
                    break
                fi
            fi
        fi
        fi
        echo "not okay" >> logs
    continue
    fi

done
        
        if [[ $vms == 2 ]];then
                sudo xm tmem-set --all weight=50  >> logs  
        fi

        if [[ $vms == 4 ]];then
                sudo xm tmem-set --all weight=25  >> logs  
        fi

##########################



target=7

if [[ $fcount -gt 2 ]];then
    target=3
fi

#target=1 #**************************************************************************************************Just for one webserver experiment

#if [[ $curr == 7 ]];then
if [[ $curr == $target ]];then
    echo finish
    echo "curr is 5 is it will end" >> logs    

    date
    echo "goind for sleep 30"   >> logs 
    sleep 30
    echo "returned from sleep"   >> logs
    date


    if [[ $vms == 1 ]];then
        echo "'" | sudo -S ./vmc1 "/home/shubhamiit/workload/change_file" >> logs
    fi

    if [[ $vms == 2 ]];then
        echo "'" | sudo -S ./vmc1 "/home/shubhamiit/workload/change_file" >> logs
        echo "'" | sudo -S ./vmc2 "/home/shubhamiit/workload/change_file" >> logs
    fi
    if [[ $vms == 4 ]];then
        echo "'" | sudo -S ./vmc1 "/home/shubhamiit/workload/change_file" >> logs
        echo "'" | sudo -S ./vmc2 "/home/shubhamiit/workload/change_file" >> logs
        echo "'" | sudo -S ./vmc3 "/home/shubhamiit/workload/change_file" >> logs
        echo "'" | sudo -S ./vmc4 "/home/shubhamiit/workload/change_file" >> logs
    fi
       


    echo 0 > current_count
    sed 's/set default=["]\([0-9]\)["]/set default="0"/' /boot/grub/grub.cfg -i
    
    fcount=$((fcount + 1))
    echo $fcount > fcount

    rm -rf expr_data_whole_"$fcount"
    mkdir expr_data_whole_"$fcount"
    echo "'" | sudo -S mv *setup*  expr_data_whole_"$fcount"
    
   # if [[ $fcount == 12 ]];then 
    if [[ $fcount == 1 ]];then 
   # if [[ $fcount == 3 ]];then 
        
        folder=`date +%y%m%d%H%M%S-results`
        mkdir $folder
        sudo cp -rf expr_data* $folder/
        

	x=`cat next`
        echo next is "$x" >> logs
        mkdir C2_before_"$x"
        sudo mv expr_data* C2_before_"$x"

	if [[ $x == "ws" ]];then
		if [[ $vms == 1 ]];then
			./vmc1 "echo 0 > /home/shubhamiit/workload/curr"
			./vmc1 "echo ws > /home/shubhamiit/workload/workload"
                	./vmc1 "/home/shubhamiit/workload/change_file" >> logs
		fi

		if [[ $vms == 2 ]];then
			./vmc1 "echo 0 > /home/shubhamiit/workload/curr"
			./vmc1 "echo ws > /home/shubhamiit/workload/workload"
                	./vmc1 "/home/shubhamiit/workload/change_file" >> logs
			./vmc2 "echo 0 > /home/shubhamiit/workload/curr"
			./vmc2 "echo ws > /home/shubhamiit/workload/workload"
                	./vmc2 "/home/shubhamiit/workload/change_file" >> logs
		fi
		if [[ $vms == 4 ]];then
			./vmc1 "echo 0 > /home/shubhamiit/workload/curr"
			./vmc1 "echo ws > /home/shubhamiit/workload/workload"
                	./vmc1 "/home/shubhamiit/workload/change_file" >> logs
			./vmc2 "echo 0 > /home/shubhamiit/workload/curr"
			./vmc2 "echo ws > /home/shubhamiit/workload/workload"
                	./vmc2 "/home/shubhamiit/workload/change_file" >> logs
			./vmc3 "echo 0 > /home/shubhamiit/workload/curr"
			./vmc3 "echo ws > /home/shubhamiit/workload/workload"
                	./vmc3 "/home/shubhamiit/workload/change_file" >> logs
			./vmc4 "echo 0 > /home/shubhamiit/workload/curr"
			./vmc4 "echo ws > /home/shubhamiit/workload/workload"
                	./vmc4 "/home/shubhamiit/workload/change_file" >> logs
		fi
		

		echo "fs" > next
    		echo 0 > current_count
    		sed 's/set default=["]\([0-9]\)["]/set default="0"/' /boot/grub/grub.cfg -i
		echo 0 > fcount
                
                echo "going for sleep 120"
                sleep 120
    
		if [[ $vm == 1 ]];then
                        sudo xm shutdown vm1
                        sleep 10
                	sudo xm destroy vm1
		fi
		if [[ $vm == 2 ]];then
                        sudo xm shutdown vm1
                        sudo xm shutdown vm2
                        sleep 10
                	sudo xm destroy vm1
			sudo xm destroy vm2
		fi
		if [[ $vm == 4 ]];then
                        sudo xm shutdown vm1
                        sudo xm shutdown vm2
                        sudo xm shutdown vm3
                        sudo xm shutdown vm4
                        sleep 10
                	sudo xm destroy vm1
			sudo xm destroy vm2
                	sudo xm destroy vm3
			sudo xm destroy vm4
		fi
	
                sudo reboot
	fi
	
	if [[ $x == "fs" ]];then
		
		if [[ $vms == 1 ]];then
			./vmc1 "echo 0 > /home/shubhamiit/workload/curr"
			./vmc1 "echo fs > /home/shubhamiit/workload/workload"
                	./vmc1 "/home/shubhamiit/workload/change_file" >> logs
		fi

		if [[ $vms == 2 ]];then
			./vmc1 "echo 0 > /home/shubhamiit/workload/curr"
			./vmc1 "echo fs > /home/shubhamiit/workload/workload"
                	./vmc1 "/home/shubhamiit/workload/change_file" >> logs
			./vmc2 "echo 0 > /home/shubhamiit/workload/curr"
			./vmc2 "echo fs > /home/shubhamiit/workload/workload"
                	./vmc2 "/home/shubhamiit/workload/change_file" >> logs
		fi
		if [[ $vms == 4 ]];then
			./vmc1 "echo 0 > /home/shubhamiit/workload/curr"
			./vmc1 "echo fs > /home/shubhamiit/workload/workload"
                	./vmc1 "/home/shubhamiit/workload/change_file" >> logs
			./vmc2 "echo 0 > /home/shubhamiit/workload/curr"
			./vmc2 "echo fs > /home/shubhamiit/workload/workload"
                	./vmc2 "/home/shubhamiit/workload/change_file" >> logs
			./vmc3 "echo 0 > /home/shubhamiit/workload/curr"
			./vmc3 "echo fs > /home/shubhamiit/workload/workload"
                	./vmc3 "/home/shubhamiit/workload/change_file" >> logs
			./vmc4 "echo 0 > /home/shubhamiit/workload/curr"
			./vmc4 "echo fs > /home/shubhamiit/workload/workload"
                	./vmc4 "/home/shubhamiit/workload/change_file" >> logs
		fi
		

		rm next
    		echo 0 > current_count
    		sed 's/set default=["]\([0-9]\)["]/set default="0"/' /boot/grub/grub.cfg -i
		echo 0 > fcount
                
                echo "going for sleep 120"
                sleep 120
		
		if [[ $vm == 1 ]];then
                        sudo xm shutdown vm1
                        sleep 10
                	sudo xm destroy vm1
		fi
		if [[ $vm == 2 ]];then
                        sudo xm shutdown vm1
                        sudo xm shutdown vm2
                        sleep 10
                	sudo xm destroy vm1
			sudo xm destroy vm2
		fi
		if [[ $vm == 4 ]];then
                        sudo xm shutdown vm1
                        sudo xm shutdown vm2
                        sudo xm shutdown vm3
                        sudo xm shutdown vm4
                        sleep 10
                	sudo xm destroy vm1
			sudo xm destroy vm2
                	sudo xm destroy vm3
			sudo xm destroy vm4
		fi
    
                sudo reboot
	fi

        echo "going for sleep 120" >> logs
        sleep 120
	
		if [[ $vm == 1 ]];then
                        sudo xm shutdown vm1
                        sudo xm shutdown vm2
                        sudo xm shutdown vm3
                        sudo xm shutdown vm4
                        sleep 10
                	sudo xm destroy vm1
		fi
		if [[ $vm == 2 ]];then
                        sudo xm shutdown vm1
                        sudo xm shutdown vm2
                        sudo xm shutdown vm3
                        sudo xm shutdown vm4
                        sleep 10
                	sudo xm destroy vm1
			sudo xm destroy vm2
		fi
		if [[ $vm == 4 ]];then
                        sudo xm shutdown vm1
                        sudo xm shutdown vm2
                        sudo xm shutdown vm3
                        sudo xm shutdown vm4
                        sleep 10
                	sudo xm destroy vm1
			sudo xm destroy vm2
                	sudo xm destroy vm3
			sudo xm destroy vm4
		fi
        echo "I am going1" >> logs
        exit 0;
    fi
    
    echo "going for sleep 120"
    sleep 120

        if [[ $vm == 1 ]];then
                sudo xm shutdown vm1
                sudo xm shutdown vm2
                sudo xm shutdown vm3
                sudo xm shutdown vm4
                sleep 10
              	sudo xm destroy vm1
	fi
	if [[ $vm == 2 ]];then
                        sudo xm shutdown vm1
                        sudo xm shutdown vm2
                        sudo xm shutdown vm3
                        sudo xm shutdown vm4
                        sleep 10
               	sudo xm destroy vm1
		sudo xm destroy vm2
	fi
	if [[ $vm == 4 ]];then
                        sudo xm shutdown vm1
                        sudo xm shutdown vm2
                        sudo xm shutdown vm3
                        sudo xm shutdown vm4
                        sleep 10
               	sudo xm destroy vm1
		sudo xm destroy vm2
               	sudo xm destroy vm3
		sudo xm destroy vm4
	fi

        
    sudo reboot

else
    echo "Benchmark started" >> logs
    date >> logs
    echo "'" | sudo ./measure_data $curr  >> logs

    echo $curr
    curr=$((curr + 1))
    echo $curr > current_count
    date >> logs
    echo "'" | sudo -S grub-reboot $curr >> logs

fi



echo "'" | sudo echo 'hi'

date >> logs
sudo grub-set-default $curr  >> logs

sed 's/set default=["]\([0-9]\)["]/set default="'$curr'"/' /boot/grub/grub.cfg -i
date >> logs
echo going for sleep 120 before reboot >> logs
sleep 120 
date >> logs
echo came from sleep and going to reboot >> logs
sleep 5

sudo reboot

